# Generated by Django 2.2.6 on 2019-11-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0003_auto_20191114_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('description', models.CharField(max_length=9)),
            ],
            options={
                'verbose_name': 'Day of the Week',
                'verbose_name_plural': 'Days of the Week',
            },
        ),
        migrations.CreateModel(
            name='OverrideDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('override_type', models.CharField(choices=[('ON', 'Always On'), ('OFF', 'Always Off')], default='OFF', max_length=3)),
            ],
            options={
                'verbose_name': 'Override Day',
                'verbose_name_plural': 'Override Days',
            },
        ),
        migrations.CreateModel(
            name='Timeframe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('days', models.ManyToManyField(blank=True, null=True, to='energy_tracker.DayOfTheWeek')),
            ],
            options={
                'verbose_name': 'Time Frame',
                'verbose_name_plural': 'Time Frame',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_time', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='energy_tracker.Timeframe')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_schedules', to='energy_tracker.Room')),
            ],
            options={
                'verbose_name': 'Room Schedule',
                'verbose_name_plural': 'Room Schedules',
            },
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_value', models.IntegerField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delay', to='energy_tracker.Device')),
            ],
            options={
                'verbose_name': 'Delay',
                'verbose_name_plural': 'Delays',
            },
        ),
    ]
