# Generated by Django 2.2.6 on 2019-11-17 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0004_dayoftheweek_delay_overrideday_schedule_timeframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('value', models.FloatField()),
            ],
            options={
                'verbose_name': 'Constant',
                'verbose_name_plural': 'Constants',
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='date_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='energy_tracker.Timeframe', verbose_name='Day and Time'),
        ),
    ]
