# Generated by Django 2.2.6 on 2019-11-17 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0005_auto_20191117_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('P', 'Power'), ('V', 'Voltage'), ('C', 'Current')], default='P', max_length=1)),
                ('value', models.FloatField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_values', to='energy_tracker.Device')),
            ],
            options={
                'verbose_name': 'Calibration Value',
                'verbose_name_plural': 'Calibration Values',
            },
        ),
        migrations.DeleteModel(
            name='Constant',
        ),
    ]
