# Generated by Django 2.0 on 2020-01-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0006_auto_20191117_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
            options={
                'verbose_name': 'Schedule Change',
                'verbose_name_plural': 'Schedule Change List',
            },
        ),
        migrations.CreateModel(
            name='ScheduleChangePairings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_pair', to='energy_tracker.Schedule')),
                ('schedule_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_date_pair', to='energy_tracker.ScheduleChange')),
            ],
        ),
    ]
