# Generated by Django 2.0 on 2020-01-25 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('energy_tracker', '0007_schedulechange_schedulechangepairings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulechangepairings',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_pair', to='energy_tracker.Timeframe'),
        ),
    ]
